### ISSUE TITLE
Designing a more flexible API

### ISSUE THREAD

**Issue by boycott670** [pivovarit/throwing-function#26]
In case you have implemented this feature, then you can ignore this issue, because i'm browsing your repository at this span [72f4d43](https://github.com/pivovarit/throwing-function/commit/72f4d43)..[8151ca6](https://github.com/pivovarit/throwing-function/commit/8151ca6).

For example let's take [ThrowingConsumer](https://github.com/pivovarit/throwing-function/blob/8151ca68121cec8ae9f8487d210d4ffc901cd36d/src/main/java/touk/pl/function/ThrowingConsumer.java)#andThenConsume method, in place of taking a `ThrowingConsumer<? super T, E>` as a parameter, why don't you take a `ThrowingConsumer<? super T, ? extends E>`, because if `this` throws an exception of type `E`, it can also handle a `ThrowingConsumer` that throws an exception of type `? extends E`.

**Comment by pivovarit** [comment]
You're absolutely right - it was just missed. 
I'm working now on the new version of the lib - if you want to contribute, I'd highly appreciate that :)

**Comment by takingsss12** [comment]
You can check my PR [here](https://github.com/pivovarit/throwing-function/pull/32).

**Comment by pivovarit** [comment]
This approach will be embraced from now on (especially in 2.0.0) - closing for now, thanks :)
