### ISSUE TITLE
Incorrect handling of InterruptedException

### ISSUE THREAD

**Issue by bazhenov** [pivovarit/throwing-function#36]
There is missing `InterruptedException` handing in `ThrowingFunction.uncheck()`.

```java
default Function<T, R> uncheck() {
    return t -> {
        try {
            return apply(t);
        } catch (final Throwable e) {
            throw new WrappedException(e);
        }
    };
}
```

If `e` is type of `InterruptedException` then interruption flag will be lost in this handler. So there should be one more `catch` clause with specific handling of `InterruptedException`.

```java
default Function<T, R> uncheck() {
    return t -> {
        try {
            return apply(t);
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt()
            throw new WrappedException(e);
        } catch (final Throwable e) {
            throw new WrappedException(e);
        }
    };
}
```

Or maybe runtime check in existing `catch`-clause.

See: https://stackoverflow.com/questions/22104097/how-does-thread-interrupt-sets-the-flag

**Comment by pivovarit** [comment]
Yes, that's a very good point - when I was writing the library I wasn't yet aware enough of these issues :)
I will prepare an update. However, this functionality will be killed in the next release
