### ISSUE TITLE
Add Try monad support

### ISSUE THREAD

**Issue by jtmthf** [pivovarit/throwing-function#37]
I find it would be useful to support wrapping throwing-function's in a `Try` monad. A `Try` is similar to an `Optional` in implementation, but specifically represents the success or failure of an operation. It is useful when the the thrown exception should be preserved in a data structure that can then be consumed in a functional manner. [jasongoodwin/better-java-monads](/jasongoodwin/better-java-monads) is a good existing implementation of a `Try` in java. 

Here is an example of what the implementation would look like for adding `Try` support to the `ThrowingFunction`.

```java
static <T, R> Function<T, Try<R>> tried(final ThrowingFunction<T, R, ?> f) {
  return requireNonNull(f).try();
}

default Function<T, Try<R>> try() {
  return t -> {
    try {
      return Try.successful(apply(t));
    } catch (final Exception e) {
      return Try.failure(e);
    }
  }
}
```

Here is a test example of usage.

```java
@Test
void shouldReturnFailedTry() {
  // given
  ThrowingFunction<Integer, Integer, Exception> f1 = givenThrowingFunction("custom exception message");

  // when
  Try<Integer> result = f1.try().apply(42);

  // then
  assertThat(result.isSuccess()).isFalse();
  assertThatThrownBy(() -> result.get())
    .isInstanceOf(Exception.class)
    .hasMessage("custom exception message");
}
```

**Comment by pivovarit** [comment]
Thanks for the suggestion, @jtmthf!

It sounds like a good idea but the thing is, if you already have `Try` on your classpath, you can easily achieve the same result without any help of this project. 

For example, let's have a look at Vavr's Try:

```
Stream.of("42")
  .map(uri -> Try.of(() -> URI.create(uri)))
  .map(t -> t.isSuccess())
```

and that's all. If we wanted to provide the feature you described, we'd need to couple to one particular `Try` implementation which is not ideal. I think that cons outweight pros in this situation.

**Comment by jtmthf** [comment]
@pivovarit Thanks for the heads up, that looks quite nice.
