### ISSUE TITLE
ThrowingIntFunction interface is not public

### ISSUE THREAD

**Issue by genzak** [pivovarit/throwing-function#45]
[`ThrowingIntFunction`](https://github.com/pivovarit/throwing-function/blob/master/src/main/java/com/pivovarit/function/ThrowingIntFunction.java#L23) interface is not `public` therefore it can't be used.

**Comment by pivovarit** [comment]
Thanks for the reminder - keep in mind that the current code is WIP and not released yet

**Comment by genzak** [comment]
Thank you for quick update.

**Comment by oilid** [comment]
Unfortunately there is still no version for this bugfix like 1.5.1?! @pivovarit

**Comment by pivovarit** [comment]
Sorry, I wanted to release that with 2.0.0 which was supposed to arrive earlier...

Anyway, I just released 1.5.1, so the fix should be in Maven Central in a few hours.

**Comment by oilid** [comment]
Wow thanks a lot!!!
