### ISSUE TITLE
Missing sneaky static method on ThrowingBinaryOperator

### ISSUE THREAD

**Issue by rwperrott** [pivovarit/throwing-function#80]
ThrowingBiFunctions method
 `static <T1, T2, R> BiFunction<T1, T2, R> sneaky(ThrowingBiFunction<? super T1, ? super T2, ? extends R, ?> function)`
can't be used directly, it'd cause a casting failure, so has to be copied like this in ThrowingBinaryOperator:
```java
    static <T> BinaryOperator<T> sneaky(ThrowingBinaryOperator<T, ?> function) {
        requireNonNull(function);
        return (t1, t2) -> {
            try {
                return function.apply(t1, t2);
            } catch (final Throwable ex) {
                return SneakyThrowUtil.sneakyThrow(ex);
            }
        };
    }
```

**Comment by rwperrott** [comment]
As mentioned in issue 79, my fix is in ThrowingBiFunctions.java in my fork at https://github.com/rwperrott/throwing-function

**Comment by rwperrott** [comment]
I'll probably move to using jOOλ, a library of jOOQ, because it covers a lot more than even my fork does for functional interfaces, so I'm closing this issue.

**Comment by pivovarit** [comment]
Too bad you did not issue a PR, good luck :)
